-- Renames PlacementInquiry -> Placement (the feature grew from a flat
-- status pipeline into a real staged lifecycle) and adds the audit trail.
-- Hand-written (not generated by `prisma migrate dev`) so existing rows are
-- preserved via RENAME rather than dropped and recreated — see
-- scripts/backfill-placement-stages.js for the follow-up data migration that
-- maps old status values onto the new stage vocabulary.

-- RenameTable
ALTER TABLE "placement_inquiries" RENAME TO "placements";

-- RenameColumn
ALTER TABLE "placements" RENAME COLUMN "status" TO "stage";
ALTER TABLE "placements" RENAME COLUMN "declined_reason" TO "closure_reason";

-- AlterTable
ALTER TABLE "placements" ALTER COLUMN "stage" SET DEFAULT 'NEW';
ALTER TABLE "placements" ADD COLUMN "specialty_care_needed" TEXT,
ADD COLUMN "assigned_to_id" TEXT;

-- AddForeignKey
ALTER TABLE "placements" ADD CONSTRAINT "placements_assigned_to_id_fkey" FOREIGN KEY ("assigned_to_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- CreateTable
CREATE TABLE "placement_events" (
    "id" TEXT NOT NULL,
    "placement_id" TEXT NOT NULL,
    "from_stage" TEXT,
    "to_stage" TEXT NOT NULL,
    "changed_by_id" TEXT,
    "note" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "placement_events_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "placement_events_placement_id_idx" ON "placement_events"("placement_id");

-- AddForeignKey
ALTER TABLE "placement_events" ADD CONSTRAINT "placement_events_placement_id_fkey" FOREIGN KEY ("placement_id") REFERENCES "placements"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "placement_events" ADD CONSTRAINT "placement_events_changed_by_id_fkey" FOREIGN KEY ("changed_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
